version: "3.9"

services:
  updater:
    build:
      context: .
      dockerfile: DuckDnsUpdater/Dockerfile
    restart: unless-stopped
    environment:
      DOMAINS: ${DOMAINS}
      TOKEN: ${TOKEN}